package com.drawnblue.entity;

import java.util.Date;

public class Affiche {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.id
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.code
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.title
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.publisher
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.publishTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private Date publishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.startTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.endTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affiche.content
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.id
     *
     * @return the value of affiche.id
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.id
     *
     * @param id the value for affiche.id
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.code
     *
     * @return the value of affiche.code
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.code
     *
     * @param code the value for affiche.code
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.title
     *
     * @return the value of affiche.title
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.title
     *
     * @param title the value for affiche.title
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.publisher
     *
     * @return the value of affiche.publisher
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.publisher
     *
     * @param publisher the value for affiche.publisher
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.publishTime
     *
     * @return the value of affiche.publishTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.publishTime
     *
     * @param publishtime the value for affiche.publishTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.startTime
     *
     * @return the value of affiche.startTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.startTime
     *
     * @param starttime the value for affiche.startTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.endTime
     *
     * @return the value of affiche.endTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.endTime
     *
     * @param endtime the value for affiche.endTime
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affiche.content
     *
     * @return the value of affiche.content
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affiche.content
     *
     * @param content the value for affiche.content
     *
     * @mbg.generated Sun Aug 04 18:07:11 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}