package com.drawnblue.entity;

import java.util.Date;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_authority.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_authority.roleId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_authority.functionId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long functionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_authority.userTypeId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long usertypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_authority.creationTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column au_authority.createdBy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String createdby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_authority.id
     *
     * @return the value of au_authority.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_authority.id
     *
     * @param id the value for au_authority.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_authority.roleId
     *
     * @return the value of au_authority.roleId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_authority.roleId
     *
     * @param roleid the value for au_authority.roleId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_authority.functionId
     *
     * @return the value of au_authority.functionId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getFunctionid() {
        return functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_authority.functionId
     *
     * @param functionid the value for au_authority.functionId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setFunctionid(Long functionid) {
        this.functionid = functionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_authority.userTypeId
     *
     * @return the value of au_authority.userTypeId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getUsertypeid() {
        return usertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_authority.userTypeId
     *
     * @param usertypeid the value for au_authority.userTypeId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUsertypeid(Long usertypeid) {
        this.usertypeid = usertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_authority.creationTime
     *
     * @return the value of au_authority.creationTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_authority.creationTime
     *
     * @param creationtime the value for au_authority.creationTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setCreationtime(Date creationtime) {
        this.creationtime = creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column au_authority.createdBy
     *
     * @return the value of au_authority.createdBy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column au_authority.createdBy
     *
     * @param createdby the value for au_authority.createdBy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }
}