package com.drawnblue.entity;

public class BasicsParameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_parameter.ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_parameter.NAME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_parameter.CODE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_parameter.VALUE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_parameter.DESCRIPTION
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_parameter.DR
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_parameter.ID
     *
     * @return the value of basics_parameter.ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_parameter.ID
     *
     * @param id the value for basics_parameter.ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_parameter.NAME
     *
     * @return the value of basics_parameter.NAME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_parameter.NAME
     *
     * @param name the value for basics_parameter.NAME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_parameter.CODE
     *
     * @return the value of basics_parameter.CODE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_parameter.CODE
     *
     * @param code the value for basics_parameter.CODE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_parameter.VALUE
     *
     * @return the value of basics_parameter.VALUE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_parameter.VALUE
     *
     * @param value the value for basics_parameter.VALUE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_parameter.DESCRIPTION
     *
     * @return the value of basics_parameter.DESCRIPTION
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_parameter.DESCRIPTION
     *
     * @param description the value for basics_parameter.DESCRIPTION
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_parameter.DR
     *
     * @return the value of basics_parameter.DR
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_parameter.DR
     *
     * @param dr the value for basics_parameter.DR
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }
}