package com.drawnblue.entity;

public class DataDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.typeCode
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String typecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.typeName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.valueId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Integer valueid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.valueName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String valuename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.id
     *
     * @return the value of data_dictionary.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.id
     *
     * @param id the value for data_dictionary.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.typeCode
     *
     * @return the value of data_dictionary.typeCode
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.typeCode
     *
     * @param typecode the value for data_dictionary.typeCode
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.typeName
     *
     * @return the value of data_dictionary.typeName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.typeName
     *
     * @param typename the value for data_dictionary.typeName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.valueId
     *
     * @return the value of data_dictionary.valueId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Integer getValueid() {
        return valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.valueId
     *
     * @param valueid the value for data_dictionary.valueId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setValueid(Integer valueid) {
        this.valueid = valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.valueName
     *
     * @return the value of data_dictionary.valueName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getValuename() {
        return valuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.valueName
     *
     * @param valuename the value for data_dictionary.valueName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setValuename(String valuename) {
        this.valuename = valuename == null ? null : valuename.trim();
    }
}