package com.drawnblue.entity;

import java.util.Date;

public class GoodsPack {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.goodsPackName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String goodspackname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.goodsPackCode
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String goodspackcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.typeId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.typeName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.totalPrice
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Double totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.state
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.num
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.createdBy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String createdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.createTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.lastUpdateTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date lastupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack.note
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.id
     *
     * @return the value of goods_pack.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.id
     *
     * @param id the value for goods_pack.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.goodsPackName
     *
     * @return the value of goods_pack.goodsPackName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getGoodspackname() {
        return goodspackname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.goodsPackName
     *
     * @param goodspackname the value for goods_pack.goodsPackName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setGoodspackname(String goodspackname) {
        this.goodspackname = goodspackname == null ? null : goodspackname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.goodsPackCode
     *
     * @return the value of goods_pack.goodsPackCode
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getGoodspackcode() {
        return goodspackcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.goodsPackCode
     *
     * @param goodspackcode the value for goods_pack.goodsPackCode
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setGoodspackcode(String goodspackcode) {
        this.goodspackcode = goodspackcode == null ? null : goodspackcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.typeId
     *
     * @return the value of goods_pack.typeId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.typeId
     *
     * @param typeid the value for goods_pack.typeId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.typeName
     *
     * @return the value of goods_pack.typeName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.typeName
     *
     * @param typename the value for goods_pack.typeName
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.totalPrice
     *
     * @return the value of goods_pack.totalPrice
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.totalPrice
     *
     * @param totalprice the value for goods_pack.totalPrice
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.state
     *
     * @return the value of goods_pack.state
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.state
     *
     * @param state the value for goods_pack.state
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.num
     *
     * @return the value of goods_pack.num
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.num
     *
     * @param num the value for goods_pack.num
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.createdBy
     *
     * @return the value of goods_pack.createdBy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.createdBy
     *
     * @param createdby the value for goods_pack.createdBy
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.createTime
     *
     * @return the value of goods_pack.createTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.createTime
     *
     * @param createtime the value for goods_pack.createTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.lastUpdateTime
     *
     * @return the value of goods_pack.lastUpdateTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.lastUpdateTime
     *
     * @param lastupdatetime the value for goods_pack.lastUpdateTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack.note
     *
     * @return the value of goods_pack.note
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack.note
     *
     * @param note the value for goods_pack.note
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}