package com.drawnblue.entity;

public class GoodsPackAffiliated {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack_affiliated.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack_affiliated.goodsPackId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long goodspackid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack_affiliated.goodsInfoId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long goodsinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_pack_affiliated.goodsNum
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Integer goodsnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack_affiliated.id
     *
     * @return the value of goods_pack_affiliated.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack_affiliated.id
     *
     * @param id the value for goods_pack_affiliated.id
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack_affiliated.goodsPackId
     *
     * @return the value of goods_pack_affiliated.goodsPackId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getGoodspackid() {
        return goodspackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack_affiliated.goodsPackId
     *
     * @param goodspackid the value for goods_pack_affiliated.goodsPackId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setGoodspackid(Long goodspackid) {
        this.goodspackid = goodspackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack_affiliated.goodsInfoId
     *
     * @return the value of goods_pack_affiliated.goodsInfoId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getGoodsinfoid() {
        return goodsinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack_affiliated.goodsInfoId
     *
     * @param goodsinfoid the value for goods_pack_affiliated.goodsInfoId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setGoodsinfoid(Long goodsinfoid) {
        this.goodsinfoid = goodsinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_pack_affiliated.goodsNum
     *
     * @return the value of goods_pack_affiliated.goodsNum
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Integer getGoodsnum() {
        return goodsnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_pack_affiliated.goodsNum
     *
     * @param goodsnum the value for goods_pack_affiliated.goodsNum
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setGoodsnum(Integer goodsnum) {
        this.goodsnum = goodsnum;
    }
}