package com.drawnblue.entity;

import java.math.BigDecimal;

public class Inventory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.GOODS_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.NUM
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.STATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.ID
     *
     * @return the value of inventory.ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.ID
     *
     * @param id the value for inventory.ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.GOODS_ID
     *
     * @return the value of inventory.GOODS_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.GOODS_ID
     *
     * @param goodsId the value for inventory.GOODS_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.NUM
     *
     * @return the value of inventory.NUM
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.NUM
     *
     * @param num the value for inventory.NUM
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.STATE
     *
     * @return the value of inventory.STATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.STATE
     *
     * @param state the value for inventory.STATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}