package com.drawnblue.entity;

public class UploadTemp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadtemp.uploader
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadtemp.uploadType
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String uploadtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadtemp.uploadFilePath
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String uploadfilepath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadtemp.uploader
     *
     * @return the value of uploadtemp.uploader
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadtemp.uploader
     *
     * @param uploader the value for uploadtemp.uploader
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadtemp.uploadType
     *
     * @return the value of uploadtemp.uploadType
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getUploadtype() {
        return uploadtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadtemp.uploadType
     *
     * @param uploadtype the value for uploadtemp.uploadType
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUploadtype(String uploadtype) {
        this.uploadtype = uploadtype == null ? null : uploadtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadtemp.uploadFilePath
     *
     * @return the value of uploadtemp.uploadFilePath
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getUploadfilepath() {
        return uploadfilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadtemp.uploadFilePath
     *
     * @param uploadfilepath the value for uploadtemp.uploadFilePath
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUploadfilepath(String uploadfilepath) {
        this.uploadfilepath = uploadfilepath == null ? null : uploadfilepath.trim();
    }
}