package com.drawnblue.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccountLogB {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.accountLogId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long accountlogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.userId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.actionTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date actiontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.actionDesc
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String actiondesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.actionType
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal actiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.baseIn
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal basein;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.baseOut
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal baseout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.baseBalance
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal basebalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.repeatIn
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal repeatin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.repeatOut
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal repeatout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_log_201404.repeatBalance
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal repeatbalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.accountLogId
     *
     * @return the value of user_account_log_201404.accountLogId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getAccountlogid() {
        return accountlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.accountLogId
     *
     * @param accountlogid the value for user_account_log_201404.accountLogId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setAccountlogid(Long accountlogid) {
        this.accountlogid = accountlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.userId
     *
     * @return the value of user_account_log_201404.userId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.userId
     *
     * @param userid the value for user_account_log_201404.userId
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.actionTime
     *
     * @return the value of user_account_log_201404.actionTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getActiontime() {
        return actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.actionTime
     *
     * @param actiontime the value for user_account_log_201404.actionTime
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setActiontime(Date actiontime) {
        this.actiontime = actiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.actionDesc
     *
     * @return the value of user_account_log_201404.actionDesc
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getActiondesc() {
        return actiondesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.actionDesc
     *
     * @param actiondesc the value for user_account_log_201404.actionDesc
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setActiondesc(String actiondesc) {
        this.actiondesc = actiondesc == null ? null : actiondesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.actionType
     *
     * @return the value of user_account_log_201404.actionType
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getActiontype() {
        return actiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.actionType
     *
     * @param actiontype the value for user_account_log_201404.actionType
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setActiontype(BigDecimal actiontype) {
        this.actiontype = actiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.baseIn
     *
     * @return the value of user_account_log_201404.baseIn
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBasein() {
        return basein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.baseIn
     *
     * @param basein the value for user_account_log_201404.baseIn
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBasein(BigDecimal basein) {
        this.basein = basein;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.baseOut
     *
     * @return the value of user_account_log_201404.baseOut
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBaseout() {
        return baseout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.baseOut
     *
     * @param baseout the value for user_account_log_201404.baseOut
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBaseout(BigDecimal baseout) {
        this.baseout = baseout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.baseBalance
     *
     * @return the value of user_account_log_201404.baseBalance
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBasebalance() {
        return basebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.baseBalance
     *
     * @param basebalance the value for user_account_log_201404.baseBalance
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBasebalance(BigDecimal basebalance) {
        this.basebalance = basebalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.repeatIn
     *
     * @return the value of user_account_log_201404.repeatIn
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getRepeatin() {
        return repeatin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.repeatIn
     *
     * @param repeatin the value for user_account_log_201404.repeatIn
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRepeatin(BigDecimal repeatin) {
        this.repeatin = repeatin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.repeatOut
     *
     * @return the value of user_account_log_201404.repeatOut
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getRepeatout() {
        return repeatout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.repeatOut
     *
     * @param repeatout the value for user_account_log_201404.repeatOut
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRepeatout(BigDecimal repeatout) {
        this.repeatout = repeatout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_log_201404.repeatBalance
     *
     * @return the value of user_account_log_201404.repeatBalance
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getRepeatbalance() {
        return repeatbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_log_201404.repeatBalance
     *
     * @param repeatbalance the value for user_account_log_201404.repeatBalance
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRepeatbalance(BigDecimal repeatbalance) {
        this.repeatbalance = repeatbalance;
    }
}