package com.drawnblue.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserPoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.POINT_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String pointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.BUY_TIME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date buyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.BONUS_USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String bonusUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal buyPv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.BONUS_RATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal bonusRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_point.BONUS_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal bonusPv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.POINT_ID
     *
     * @return the value of user_point.POINT_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.POINT_ID
     *
     * @param pointId the value for user_point.POINT_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setPointId(String pointId) {
        this.pointId = pointId == null ? null : pointId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.BUY_TIME
     *
     * @return the value of user_point.BUY_TIME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.BUY_TIME
     *
     * @param buyTime the value for user_point.BUY_TIME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.BONUS_USER_ID
     *
     * @return the value of user_point.BONUS_USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getBonusUserId() {
        return bonusUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.BONUS_USER_ID
     *
     * @param bonusUserId the value for user_point.BONUS_USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBonusUserId(String bonusUserId) {
        this.bonusUserId = bonusUserId == null ? null : bonusUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.USER_ID
     *
     * @return the value of user_point.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.USER_ID
     *
     * @param userId the value for user_point.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.BUY_PV
     *
     * @return the value of user_point.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBuyPv() {
        return buyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.BUY_PV
     *
     * @param buyPv the value for user_point.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBuyPv(BigDecimal buyPv) {
        this.buyPv = buyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.BONUS_RATE
     *
     * @return the value of user_point.BONUS_RATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBonusRate() {
        return bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.BONUS_RATE
     *
     * @param bonusRate the value for user_point.BONUS_RATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBonusRate(BigDecimal bonusRate) {
        this.bonusRate = bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_point.BONUS_PV
     *
     * @return the value of user_point.BONUS_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBonusPv() {
        return bonusPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_point.BONUS_PV
     *
     * @param bonusPv the value for user_point.BONUS_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBonusPv(BigDecimal bonusPv) {
        this.bonusPv = bonusPv;
    }
}