package com.drawnblue.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserRefer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.REFER_LOG_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String referLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.REFER_TIME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date referTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.REFER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String referId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal buyPv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.BONUS_RATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal bonusRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_refer.BONUS_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal bonusPv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.REFER_LOG_ID
     *
     * @return the value of user_refer.REFER_LOG_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getReferLogId() {
        return referLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.REFER_LOG_ID
     *
     * @param referLogId the value for user_refer.REFER_LOG_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setReferLogId(String referLogId) {
        this.referLogId = referLogId == null ? null : referLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.REFER_TIME
     *
     * @return the value of user_refer.REFER_TIME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getReferTime() {
        return referTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.REFER_TIME
     *
     * @param referTime the value for user_refer.REFER_TIME
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setReferTime(Date referTime) {
        this.referTime = referTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.USER_ID
     *
     * @return the value of user_refer.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.USER_ID
     *
     * @param userId the value for user_refer.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.REFER_ID
     *
     * @return the value of user_refer.REFER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getReferId() {
        return referId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.REFER_ID
     *
     * @param referId the value for user_refer.REFER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setReferId(String referId) {
        this.referId = referId == null ? null : referId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.BUY_PV
     *
     * @return the value of user_refer.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBuyPv() {
        return buyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.BUY_PV
     *
     * @param buyPv the value for user_refer.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBuyPv(BigDecimal buyPv) {
        this.buyPv = buyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.BONUS_RATE
     *
     * @return the value of user_refer.BONUS_RATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBonusRate() {
        return bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.BONUS_RATE
     *
     * @param bonusRate the value for user_refer.BONUS_RATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBonusRate(BigDecimal bonusRate) {
        this.bonusRate = bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_refer.BONUS_PV
     *
     * @return the value of user_refer.BONUS_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBonusPv() {
        return bonusPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_refer.BONUS_PV
     *
     * @param bonusPv the value for user_refer.BONUS_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBonusPv(BigDecimal bonusPv) {
        this.bonusPv = bonusPv;
    }
}