package com.drawnblue.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserAccountA {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.ACCOUNT_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.ACCOUNT_DATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private Date accountDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.STAT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal stat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.BASE_IN
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal baseIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.BASE_OUT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal baseOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.BASE_BALANCE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal baseBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.REPEAT_IN
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal repeatIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.REPEAT_OUT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal repeatOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.REPEAT_BALANCE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal repeatBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.FREE_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal freePv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.ALREADY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal alreadyPv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_201312.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    private BigDecimal buyPv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.ACCOUNT_ID
     *
     * @return the value of user_account_201312.ACCOUNT_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.ACCOUNT_ID
     *
     * @param accountId the value for user_account_201312.ACCOUNT_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.USER_ID
     *
     * @return the value of user_account_201312.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.USER_ID
     *
     * @param userId the value for user_account_201312.USER_ID
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.ACCOUNT_DATE
     *
     * @return the value of user_account_201312.ACCOUNT_DATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public Date getAccountDate() {
        return accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.ACCOUNT_DATE
     *
     * @param accountDate the value for user_account_201312.ACCOUNT_DATE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setAccountDate(Date accountDate) {
        this.accountDate = accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.STAT
     *
     * @return the value of user_account_201312.STAT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.STAT
     *
     * @param stat the value for user_account_201312.STAT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setStat(BigDecimal stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.BASE_IN
     *
     * @return the value of user_account_201312.BASE_IN
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBaseIn() {
        return baseIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.BASE_IN
     *
     * @param baseIn the value for user_account_201312.BASE_IN
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBaseIn(BigDecimal baseIn) {
        this.baseIn = baseIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.BASE_OUT
     *
     * @return the value of user_account_201312.BASE_OUT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBaseOut() {
        return baseOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.BASE_OUT
     *
     * @param baseOut the value for user_account_201312.BASE_OUT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBaseOut(BigDecimal baseOut) {
        this.baseOut = baseOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.BASE_BALANCE
     *
     * @return the value of user_account_201312.BASE_BALANCE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBaseBalance() {
        return baseBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.BASE_BALANCE
     *
     * @param baseBalance the value for user_account_201312.BASE_BALANCE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBaseBalance(BigDecimal baseBalance) {
        this.baseBalance = baseBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.REPEAT_IN
     *
     * @return the value of user_account_201312.REPEAT_IN
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getRepeatIn() {
        return repeatIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.REPEAT_IN
     *
     * @param repeatIn the value for user_account_201312.REPEAT_IN
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRepeatIn(BigDecimal repeatIn) {
        this.repeatIn = repeatIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.REPEAT_OUT
     *
     * @return the value of user_account_201312.REPEAT_OUT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getRepeatOut() {
        return repeatOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.REPEAT_OUT
     *
     * @param repeatOut the value for user_account_201312.REPEAT_OUT
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRepeatOut(BigDecimal repeatOut) {
        this.repeatOut = repeatOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.REPEAT_BALANCE
     *
     * @return the value of user_account_201312.REPEAT_BALANCE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getRepeatBalance() {
        return repeatBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.REPEAT_BALANCE
     *
     * @param repeatBalance the value for user_account_201312.REPEAT_BALANCE
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setRepeatBalance(BigDecimal repeatBalance) {
        this.repeatBalance = repeatBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.FREE_PV
     *
     * @return the value of user_account_201312.FREE_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getFreePv() {
        return freePv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.FREE_PV
     *
     * @param freePv the value for user_account_201312.FREE_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setFreePv(BigDecimal freePv) {
        this.freePv = freePv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.ALREADY_PV
     *
     * @return the value of user_account_201312.ALREADY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getAlreadyPv() {
        return alreadyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.ALREADY_PV
     *
     * @param alreadyPv the value for user_account_201312.ALREADY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setAlreadyPv(BigDecimal alreadyPv) {
        this.alreadyPv = alreadyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_201312.BUY_PV
     *
     * @return the value of user_account_201312.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public BigDecimal getBuyPv() {
        return buyPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_201312.BUY_PV
     *
     * @param buyPv the value for user_account_201312.BUY_PV
     *
     * @mbg.generated Sun Aug 04 18:07:12 CST 2019
     */
    public void setBuyPv(BigDecimal buyPv) {
        this.buyPv = buyPv;
    }
}